---
- name: Cleanup jnv.unattended-updates
  file:
    path: '/etc/apt/apt.conf.d/20auto-upgrades.ucf-dist'
    state: absent
- name: Install update-notifier-common
  apt:
    pkg: update-notifier-common
    state: latest
    force: yes
