---
- name: Setup deploy user
  user:
    name: "{{ deployer }}"
    comment: "deploy user"
    state: present
    shell: '/bin/bash'
    home: "{{ deployer_home_dir }}"

- name: Set up authorized_keys for admin user
  authorized_key:
    user: "{{ root_user }}"
    key: "{{ item }}"
  with_file:
    - "{{ sudoers_path }}"

- name: Set up authorized_keys for app deployment user
  authorized_key:
    user: "{{ deployer }}"
    key: "{{ item }}"
  with_file:
    - "{{ deployers_path }}"

- name: Include tasks to fix jnv.unattended-updates
  include: jnv.unattended-updates.yml

- name: apt-get update
  apt:
    update_cache: yes

- name: Install build and system tools
  apt:
    pkg:
      - git
      - ntp
      - build-essential
      - htop
      - nodejs
    state: latest

- name: Set up Datadog
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ secrets.datadog_api_key }}"
  tags:
    - datadog

- name: Install database clients
  apt:
    pkg:
      - libpq-dev
      - postgresql-client
    state: latest

- name: Install logrotate
  apt:
    pkg: logrotate
    state: present

- name: Configure NGINX Log Rotation
  template:
    src: logrotate.nginx
    dest: '/etc/logrotate.d/nginx'
    owner: root
    group: root

- name: Configure RAILS Log Rotation
  template:
    src: logrotate.rails
    dest: '/etc/logrotate.d/rails'
    owner: root
    group: root

- name: Configure CRON Log Rotation
  template:
    src: logrotate.cron
    dest: '/etc/cron.daily/logrotate'
    owner: root
    group: root

- name: Get latest version of vim
  apt:
    pkg: vim
    state: latest

- name: Set vim as the default editor
  file:
    src: '/usr/bin/vim'
    dest: '/etc/alternatives/editor'
    state: link
